### ISSUE TITLE
Add a healthy check in docker Compose for the DB

### ISSUE THREAD

**Issue by epicserve** [epicserve/django-base-site#1135]
Soemthing like:
```yaml
healthcheck:
  test: [ "CMD-SHELL", "pg_isready -U arc" ]
  # Check every second during the first 30 seconds.
  start_interval: 1s
  start_period: 30s
  # Afterwards, only check every 30 seconds.
  interval: 30s
  timeout: 5s
  retries: 30
```
